web:
  # image: seeddigital/realtrendz_web
  build: .
  # command: "node app"
  ports:
    - "3000:8080"
  links:
    - realtrends_es:realtrends_es
  volumes:
    - "./app:/app"
  environment:
    - 
realtrends_es:
  build: devops/elasicsearch/
  ports:
    - "9200:9200"
  volumes:
   - "esdatas:/usr/share/elasticsearch/data"